### ISSUE TITLE
Replace tabs indenting with spaces

### ISSUE THREAD

**Issue by 102** [mapsme/borders#3]
According to [PEP](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces):

> Spaces are the preferred indentation method.

**Comment by Zverik** [comment]
What bug would it fix?

**Comment by 102** [comment]
@Zverik it doesn't tied with any bugs, but it's about following de-facto standard python style guide. To be honest, I'm not sure that it's possible to find any style guide in 2016, which recommends to indent code with tabs (e.g. [google's style guide for python](https://google.github.io/styleguide/pyguide.html#Indentation) recommends 4 spaces as well)

**Comment by Zverik** [comment]
Why should I follow the style guide in the matter of spaces vs tabs in this case? What would be made better?

**Comment by 102** [comment]
I'm not sure there's any objective pros, just mentioned pep violation.  Feel free to close this as non-constructive

**Comment by Zverik** [comment]
You cannot violate a recommendation, just follow or not follow it. I decided to use tabs for this project, and unless there is some noticeable issue with that, they will remain.
